repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python]
        args: [--fix, --select, "I"]
      # Run the formatter.
      - id: ruff-format
        types_or: [python]
        args: [--line-length, "120"]