# I/O settings
wandb_logging: True
wandb_project: "hicric" # required if wandb_logging is True
wandb_run_tag: "outcome_prediction" # required if wandb_logging is True

# Model + data settings
hicric_pretrained: True
base_model_name: "distilbert"
pretrained_model_dir: "./models_w_config/fill_mask/distilbert-base-uncased/checkpoint-853850"
pretrained_hf_model_key: "distilbert/distilbert-base-uncased"
train_data_path: "./data/outcomes/train_backgrounds_suff.jsonl"

# Training settings
learning_rate: 8.0e-7
weight_decay: 0.01
num_epochs: 40
batch_size: 20
dtype: "float16"  # 'float32','float16' for training dtype
compile: True # Whether to use torch compile

# Test eval settings
test_data_path: "./data/outcomes/test_backgrounds_suff.jsonl"
checkpoint_name: "checkpoint-47780"
eval_threshold: .65